#!/usr/bin/env bash
# charts/gateway-projects carries the templates of gateway-groups and
# gateway-policies as named templates, so one release renders every
# project's ListenerSets AND its policies, and one Application can be a
# single chart. The two charts stay the single source; this script is the
# only writer of the generated files, and CI runs `check`.
#
#   hack/sync-gateway-projects.sh          regenerate
#   hack/sync-gateway-projects.sh check    fail when the generated files are stale
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
dst="$root/charts/gateway-projects"
mode="${1:-write}"
out="$(mktemp -d)"
trap 'rm -rf "$out"' EXIT
mkdir -p "$out/templates" "$out/files"

banner='{{- /* GENERATED by hack/sync-gateway-projects.sh from charts/%s: do not edit. */ -}}'

for chart in gateway-groups gateway-policies; do
  short="${chart#gateway-}"
  for f in "$root/charts/$chart/templates"/*; do
    name="$(basename "$f")"
    if [ "$name" = _helpers.tpl ]; then
      { printf "$banner\n" "$chart"; cat "$f"; } > "$out/templates/_${short}-helpers.tpl"
      continue
    fi
    base="${name%.yaml}"
    {
      printf "$banner\n" "$chart"
      echo "{{- define \"gateway-projects.$short.$base\" -}}"
      cat "$f"
      echo
      echo "{{- end -}}"
    } > "$out/templates/_${short}-$base.tpl"
  done
  cp "$root/charts/$chart/values.yaml" "$out/files/$chart-defaults.yaml"
done

if [ "$mode" = check ]; then
  for g in "$out"/templates/* "$out"/files/*; do
    rel="${g#"$out"/}"
    cmp -s "$g" "$dst/$rel" || { echo "stale: charts/gateway-projects/$rel (run hack/sync-gateway-projects.sh)" >&2; exit 1; }
  done
  exit 0
fi

cp "$out"/templates/* "$dst/templates/"
cp "$out"/files/* "$dst/files/"
