name: Devbox Update

on:
  schedule:
    - cron: "0 1 * * *" # daily: go directive aligned every day, full devbox update on Monday (mode auto)
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update:
    uses: truvity/ci-workflows/.github/workflows/devbox-update.yaml@ee73220eb9cb488f4a19f636307cddc85fc602bc # v2.16.1
    secrets: inherit
