name: Devbox Update

on:
  schedule:
    - cron: "0 1 * * *" # daily: go directive aligned every day, full devbox update on Monday (mode auto)
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update:
    uses: truvity/ci-workflows/.github/workflows/devbox-update.yaml@b19968438f6f19b681517c4e2cfcb87fe7887673 # v2.16.3
    secrets: inherit
